tag = "astraplani-config_systems"
writes = [
    "astraplani-DustValueConfig",
    "astraplani-DustEmissionConfig",
    "astraplani-HarvestTimeConfig",
    "astraplani-BaseCosmicBodyMassConfig",
    "astraplani-MinOrbitCenterMassConfig",
    "astraplani-MaxCosmicBodyMassConfig",
    "astraplani-LooshCostConfig",
    "astraplani-TravelSpeedConfig",
    "astraplani-AdminConfig",
    "astraplani-IncubationTimeConfig"
]
