kind = "DojoModel"
class_hash = "0x1fa45363d21c02700b7f403180c15937cf2cf003b2a87c87ef9f8c6b628c9a7"
original_class_hash = "0x1fa45363d21c02700b7f403180c15937cf2cf003b2a87c87ef9f8c6b628c9a7"
abi = "manifests/dev/base/abis/models/astraplani-MaxCosmicBodyMassConfig-4544d1d4.json"
tag = "astraplani-MaxCosmicBodyMassConfig"
qualified_path = "astraplani::models::config::max_cosmic_body_mass_config"
manifest_name = "astraplani-MaxCosmicBodyMassConfig-4544d1d4"

[[members]]
name = "config_id"
type = "u32"
key = true

[[members]]
name = "max_asteroid_cluster_mass"
type = "u64"
key = false
