kind = "DojoModel"
class_hash = "0x2ab8e3a3065755c0ee38da65ce6229dfdbdaead3bd496462e625dd46e4cc2fc"
original_class_hash = "0x2ab8e3a3065755c0ee38da65ce6229dfdbdaead3bd496462e625dd46e4cc2fc"
abi = "manifests/dev/base/abis/models/astraplani-DustValueConfig-6299caf9.json"
tag = "astraplani-DustValueConfig"
qualified_path = "astraplani::models::config::dust_value_config"
manifest_name = "astraplani-DustValueConfig-6299caf9"

[[members]]
name = "config_id"
type = "u32"
key = true

[[members]]
name = "mass_to_dust"
type = "u128"
key = false
