kind = "DojoModel"
class_hash = "0x7c86fc95712b71dd40a81f94531e051f180ba5664bd68fca1c31a279470d7a2"
original_class_hash = "0x7c86fc95712b71dd40a81f94531e051f180ba5664bd68fca1c31a279470d7a2"
abi = "manifests/dev/base/abis/models/astraplani-Incubation-7b61c0be.json"
tag = "astraplani-Incubation"
qualified_path = "astraplani::models::incubation::incubation"
manifest_name = "astraplani-Incubation-7b61c0be"

[[members]]
name = "entity"
type = "u32"
key = true

[[members]]
name = "creation_ts"
type = "u64"
key = false

[[members]]
name = "end_ts"
type = "u64"
key = false
