kind = "DojoModel"
class_hash = "0x6351e565bcd7dfeb4c89ef724dda3ca7b7a226a07ec54b83c4cec0386aed2f9"
original_class_hash = "0x6351e565bcd7dfeb4c89ef724dda3ca7b7a226a07ec54b83c4cec0386aed2f9"
abi = "manifests/dev/base/abis/models/astraplani-StarFormed-1620486d.json"
tag = "astraplani-StarFormed"
qualified_path = "astraplani::systems::creation::contracts::creation_systems::creation_systems::star_formed"
manifest_name = "astraplani-StarFormed-1620486d"

[[members]]
name = "body_id"
type = "u32"
key = true

[[members]]
name = "creation_ts"
type = "u64"
key = false
