kind = "DojoModel"
class_hash = "0x5aac421e8bad94b514300c9b1c218d0c8384cd61cb64d46cfedeb10be61daaf"
original_class_hash = "0x5aac421e8bad94b514300c9b1c218d0c8384cd61cb64d46cfedeb10be61daaf"
abi = "manifests/dev/base/abis/models/astraplani-OrbitEntered-67e52916.json"
tag = "astraplani-OrbitEntered"
qualified_path = "astraplani::systems::movement::contracts::movement_systems::movement_systems::orbit_entered"
manifest_name = "astraplani-OrbitEntered-67e52916"

[[members]]
name = "body_id"
type = "u32"
key = true

[[members]]
name = "orbit_center"
type = "u32"
key = false
