kind = "DojoModel"
class_hash = "0x3eac911089f6d10127ba5b59bb103a3c53e43468dbdede610e6d73d854d8c9c"
original_class_hash = "0x3eac911089f6d10127ba5b59bb103a3c53e43468dbdede610e6d73d854d8c9c"
abi = "manifests/dev/base/abis/models/astraplani-DustConsumed-2b00642b.json"
tag = "astraplani-DustConsumed"
qualified_path = "astraplani::systems::dust::contracts::dust_systems::dust_systems::dust_consumed"
manifest_name = "astraplani-DustConsumed-2b00642b"

[[members]]
name = "body_id"
type = "u32"
key = true

[[members]]
name = "amount"
type = "u128"
key = false
