kind = "DojoModel"
class_hash = "0x4935872985dffdd6e2182d54db1723214535b3098641189880e5dbe183f336"
original_class_hash = "0x4935872985dffdd6e2182d54db1723214535b3098641189880e5dbe183f336"
abi = "manifests/dev/base/abis/models/astraplani-AsteroidsFormed-f6059257.json"
tag = "astraplani-AsteroidsFormed"
qualified_path = "astraplani::systems::creation::contracts::creation_systems::creation_systems::asteroids_formed"
manifest_name = "astraplani-AsteroidsFormed-f6059257"

[[members]]
name = "body_id"
type = "u32"
key = true

[[members]]
name = "mass"
type = "u64"
key = false

[[members]]
name = "creation_ts"
type = "u64"
key = false
