kind = "DojoModel"
class_hash = "0x3df76b2e96480bd7382db3723e960a54dec66ceac6ff529e419d831aff136ea"
original_class_hash = "0x3df76b2e96480bd7382db3723e960a54dec66ceac6ff529e419d831aff136ea"
abi = "manifests/dev/base/abis/models/astraplani-BaseCosmicBodyMassConfig-6a3367f2.json"
tag = "astraplani-BaseCosmicBodyMassConfig"
qualified_path = "astraplani::models::config::base_cosmic_body_mass_config"
manifest_name = "astraplani-BaseCosmicBodyMassConfig-6a3367f2"

[[members]]
name = "config_id"
type = "u32"
key = true

[[members]]
name = "base_star_mass"
type = "u64"
key = false

[[members]]
name = "base_quasar_mass"
type = "u64"
key = false
