kind = "DojoModel"
class_hash = "0x5c54743d28766a0f14139017cb83e7a4432b6ff6fb3de0319fd7713a70e6f4d"
original_class_hash = "0x5c54743d28766a0f14139017cb83e7a4432b6ff6fb3de0319fd7713a70e6f4d"
abi = "manifests/dev/base/abis/models/astraplani-MinOrbitCenterMassConfig-7f0ba727.json"
tag = "astraplani-MinOrbitCenterMassConfig"
qualified_path = "astraplani::models::config::min_orbit_center_mass_config"
manifest_name = "astraplani-MinOrbitCenterMassConfig-7f0ba727"

[[members]]
name = "config_id"
type = "u32"
key = true

[[members]]
name = "min_mass_multiplier"
type = "u64"
key = false
