kind = "DojoModel"
class_hash = "0x76bb37f9250d1572e20a288ff7bd9e5c1d072fc37259bebf2ff0884dc4933a2"
original_class_hash = "0x76bb37f9250d1572e20a288ff7bd9e5c1d072fc37259bebf2ff0884dc4933a2"
abi = "manifests/dev/base/abis/models/astraplani-DustPoolExited-dd0de7b6.json"
tag = "astraplani-DustPoolExited"
qualified_path = "astraplani::systems::dust::contracts::dust_systems::dust_systems::dust_pool_exited"
manifest_name = "astraplani-DustPoolExited-dd0de7b6"

[[members]]
name = "body_id"
type = "u32"
key = true

[[members]]
name = "pool_id"
type = "u32"
key = false
