kind = "DojoModel"
class_hash = "0x7a6d91743a3876f3a10aa3c92c0ca4f83d73d6ca27260bb4b20758077fa77b5"
original_class_hash = "0x7a6d91743a3876f3a10aa3c92c0ca4f83d73d6ca27260bb4b20758077fa77b5"
abi = "manifests/dev/base/abis/models/astraplani-BodyMassChange-3c294267.json"
tag = "astraplani-BodyMassChange"
qualified_path = "astraplani::systems::mass::contracts::mass_systems::mass_systems::body_mass_change"
manifest_name = "astraplani-BodyMassChange-3c294267"

[[members]]
name = "body_id"
type = "u32"
key = true

[[members]]
name = "old_mass"
type = "u64"
key = false

[[members]]
name = "new_mass"
type = "u64"
key = false
