kind = "DojoModel"
class_hash = "0x29dcb7e74cf6f1c5e2a1e065b6d664186bd3b00f737dfef559ef8d3f90e9938"
original_class_hash = "0x29dcb7e74cf6f1c5e2a1e065b6d664186bd3b00f737dfef559ef8d3f90e9938"
abi = "manifests/dev/base/abis/models/astraplani-DustEmissionConfig-2a496654.json"
tag = "astraplani-DustEmissionConfig"
qualified_path = "astraplani::models::config::dust_emission_config"
manifest_name = "astraplani-DustEmissionConfig-2a496654"

[[members]]
name = "config_id"
type = "u32"
key = true

[[members]]
name = "base_dust_emission"
type = "u128"
key = false
