kind = "DojoModel"
class_hash = "0x49b7d2ec0b6f3bee403b9c0cb41a66e0ea241d91146b7811929d236811563e1"
original_class_hash = "0x49b7d2ec0b6f3bee403b9c0cb41a66e0ea241d91146b7811929d236811563e1"
abi = "manifests/dev/base/abis/models/astraplani-BasalAttributes-2c5f30dc.json"
tag = "astraplani-BasalAttributes"
qualified_path = "astraplani::models::basal_attributes::basal_attributes"
manifest_name = "astraplani-BasalAttributes-2c5f30dc"

[[members]]
name = "entity"
type = "u32"
key = true

[[members]]
name = "attributes"
type = "u8"
key = false
