kind = "DojoModel"
class_hash = "0x12db79fd2eddb0a93f95cfa1642759a3748e33b7dae7ea6d1a5f3df29a453a"
original_class_hash = "0x12db79fd2eddb0a93f95cfa1642759a3748e33b7dae7ea6d1a5f3df29a453a"
abi = "manifests/dev/base/abis/models/astraplani-LooshCostConfig-28c6fe8a.json"
tag = "astraplani-LooshCostConfig"
qualified_path = "astraplani::models::config::loosh_cost_config"
manifest_name = "astraplani-LooshCostConfig-28c6fe8a"

[[members]]
name = "config_id"
type = "u32"
key = true

[[members]]
name = "base_travel_cost"
type = "u128"
key = false

[[members]]
name = "base_creation_cost"
type = "u128"
key = false
