kind = "DojoModel"
class_hash = "0x115a4ec64064559dbfe1206be912c374292d9b65c54db18cf065100e9809f72"
original_class_hash = "0x115a4ec64064559dbfe1206be912c374292d9b65c54db18cf065100e9809f72"
abi = "manifests/dev/base/abis/models/astraplani-DustCloud-684cfec4.json"
tag = "astraplani-DustCloud"
qualified_path = "astraplani::models::dust_cloud::dust_cloud"
manifest_name = "astraplani-DustCloud-684cfec4"

[[members]]
name = "x"
type = "u64"
key = true

[[members]]
name = "y"
type = "u64"
key = true

[[members]]
name = "orbit_center"
type = "u32"
key = true

[[members]]
name = "dust_balance"
type = "u128"
key = false
