kind = "DojoModel"
class_hash = "0x506b531786a16f0550aec7877641a259637f04755244794c2f9d51c0faf98d1"
original_class_hash = "0x506b531786a16f0550aec7877641a259637f04755244794c2f9d51c0faf98d1"
abi = "manifests/dev/base/abis/models/astraplani-QuasarCreated-4fa24656.json"
tag = "astraplani-QuasarCreated"
qualified_path = "astraplani::systems::creation::contracts::creation_systems::creation_systems::quasar_created"
manifest_name = "astraplani-QuasarCreated-4fa24656"

[[members]]
name = "body_id"
type = "u32"
key = true

[[members]]
name = "owner"
type = "ContractAddress"
key = false

[[members]]
name = "mass"
type = "u64"
key = false

[[members]]
name = "coords"
type = "Vec2"
key = false

[[members]]
name = "parent_id"
type = "u32"
key = false

[[members]]
name = "creation_ts"
type = "u64"
key = false
