kind = "DojoModel"
class_hash = "0x68322dcf43ec1ce00d5475aa9e106863f80afd7dc25970afb8328637862f5ed"
original_class_hash = "0x68322dcf43ec1ce00d5475aa9e106863f80afd7dc25970afb8328637862f5ed"
abi = "manifests/dev/base/abis/models/astraplani-DustPoolEntered-3c8efb40.json"
tag = "astraplani-DustPoolEntered"
qualified_path = "astraplani::systems::dust::contracts::dust_systems::dust_systems::dust_pool_entered"
manifest_name = "astraplani-DustPoolEntered-3c8efb40"

[[members]]
name = "body_id"
type = "u32"
key = true

[[members]]
name = "pool_id"
type = "u32"
key = false
