kind = "DojoModel"
class_hash = "0x3da7dc5a004da6b450e2706925859633b2e6121095ff7c399df30860e0568da"
original_class_hash = "0x3da7dc5a004da6b450e2706925859633b2e6121095ff7c399df30860e0568da"
abi = "manifests/dev/base/abis/models/astraplani-IncubationTimeConfig-5059cc31.json"
tag = "astraplani-IncubationTimeConfig"
qualified_path = "astraplani::models::config::incubation_time_config"
manifest_name = "astraplani-IncubationTimeConfig-5059cc31"

[[members]]
name = "config_id"
type = "u32"
key = true

[[members]]
name = "base_incubation_time"
type = "u64"
key = false
