kind = "DojoModel"
class_hash = "0x270f2915206dab5bf243c86b329b804eb0b445ebbb638c80802e64fc763a3bd"
original_class_hash = "0x270f2915206dab5bf243c86b329b804eb0b445ebbb638c80802e64fc763a3bd"
abi = "manifests/dev/base/abis/models/astraplani-HarvestActionEnded-6a6fc682.json"
tag = "astraplani-HarvestActionEnded"
qualified_path = "astraplani::systems::dust::contracts::dust_systems::dust_systems::harvest_action_ended"
manifest_name = "astraplani-HarvestActionEnded-6a6fc682"

[[members]]
name = "body_id"
type = "u32"
key = true

[[members]]
name = "cloud_coords"
type = "Vec2"
key = false

[[members]]
name = "amount"
type = "u128"
key = false
