kind = "DojoModel"
class_hash = "0xb1bfc89b4ae65024fb01b3cc45b0334f04bf10808647bd20bd7e6169f05f6b"
original_class_hash = "0xb1bfc89b4ae65024fb01b3cc45b0334f04bf10808647bd20bd7e6169f05f6b"
abi = "manifests/dev/base/abis/models/astraplani-HarvestActionBegan-6b68eda5.json"
tag = "astraplani-HarvestActionBegan"
qualified_path = "astraplani::systems::dust::contracts::dust_systems::dust_systems::harvest_action_began"
manifest_name = "astraplani-HarvestActionBegan-6b68eda5"

[[members]]
name = "body_id"
type = "u32"
key = true

[[members]]
name = "cloud_coords"
type = "Vec2"
key = false

[[members]]
name = "amount"
type = "u128"
key = false

[[members]]
name = "harvest_end_ts"
type = "u64"
key = false
