kind = "DojoModel"
class_hash = "0x1f8ac80701df2e4171c18aa80a1840f2157ab88700e4abe1cf316d2c53f58ae"
original_class_hash = "0x1f8ac80701df2e4171c18aa80a1840f2157ab88700e4abe1cf316d2c53f58ae"
abi = "manifests/dev/base/abis/models/astraplani-HarvestTimeConfig-7be95585.json"
tag = "astraplani-HarvestTimeConfig"
qualified_path = "astraplani::models::config::harvest_time_config"
manifest_name = "astraplani-HarvestTimeConfig-7be95585"

[[members]]
name = "config_id"
type = "u32"
key = true

[[members]]
name = "min_harvest_time"
type = "u64"
key = false

[[members]]
name = "base_harvest_time"
type = "u64"
key = false
