kind = "DojoModel"
class_hash = "0x46f15a4778a644289cec8681efb3fc6864e3683ad7e6c4e499cd901e646c233"
original_class_hash = "0x46f15a4778a644289cec8681efb3fc6864e3683ad7e6c4e499cd901e646c233"
abi = "manifests/dev/base/abis/models/astraplani-DustPoolMassChange-37dc0e5c.json"
tag = "astraplani-DustPoolMassChange"
qualified_path = "astraplani::systems::dust::contracts::dust_systems::dust_systems::dust_pool_mass_change"
manifest_name = "astraplani-DustPoolMassChange-37dc0e5c"

[[members]]
name = "body_id"
type = "u32"
key = true

[[members]]
name = "old_mass"
type = "u64"
key = false

[[members]]
name = "new_mass"
type = "u64"
key = false
