kind = "DojoModel"
class_hash = "0x7ea021d5b71228c59d1516b271eeb181bb70b5d4e22e17c8ee86d5e053ff465"
original_class_hash = "0x7ea021d5b71228c59d1516b271eeb181bb70b5d4e22e17c8ee86d5e053ff465"
abi = "manifests/dev/base/abis/models/astraplani-HarvestActionCancelled-58507009.json"
tag = "astraplani-HarvestActionCancelled"
qualified_path = "astraplani::systems::dust::contracts::dust_systems::dust_systems::harvest_action_cancelled"
manifest_name = "astraplani-HarvestActionCancelled-58507009"

[[members]]
name = "body_id"
type = "u32"
key = true

[[members]]
name = "cloud_coords"
type = "Vec2"
key = false
