kind = "DojoModel"
class_hash = "0x2ff5bac833d0e727063a08e5500e0c32f881d59f1cbff4feb7f99e533ee448e"
original_class_hash = "0x2ff5bac833d0e727063a08e5500e0c32f881d59f1cbff4feb7f99e533ee448e"
abi = "manifests/dev/base/abis/models/astraplani-DustPoolFormed-12e4068a.json"
tag = "astraplani-DustPoolFormed"
qualified_path = "astraplani::systems::dust::contracts::dust_systems::dust_systems::dust_pool_formed"
manifest_name = "astraplani-DustPoolFormed-12e4068a"

[[members]]
name = "body_id"
type = "u32"
key = true

[[members]]
name = "emission_rate"
type = "u128"
key = false
