[world]
name = "Astraplani"
description = "The official Astraplani contracts"
cover_uri = "file://assets/cover.png"
icon_uri = "file://assets/icon.png"
website = "https://github.com/dojoengine/dojo-starter"
seed = "astraplani"

[world.socials]
x = "https://x.com/ohayo_dojo"
discord = "https://discord.gg/FB2wR6uF"
github = "https://github.com/dojoengine/dojo-starter"
telegram = "https://t.me/dojoengine"

[namespace]
default = "ns"

[env]
rpc_url = "http://localhost:5050/"
# Default account for katana with seed = 0
account_address = "0x127fd5f1fe78a71f8bcd1fec63e3fe2f0486b6ecd5c86a0466c3a21fa5cfcec"
private_key = "0xc5b2fcab997346f3ea1c00b002ecf6f382c5f9c9659a3894eb783c5320f912"
world_address = "0x4295290583f526b75ee4c82495a66abdb63ade654c1499b1619cd2497ecfa3b"

[writers]
"ns" = [
    "ns-authority_systems",
    "ns-config_systems",
    "ns-creation_systems",
    "ns-dust_systems",
    "ns-loosh_systems",
    "ns-mass_systems",
    "ns-movement_systems",
]