[package]
cairo-version = "=2.8.4"
name = "astraplani"
version = "0.1.0"

[cairo]
sierra-replace-ids = true

[scripts]
dev = "./scripts/dev.sh"
torii = "./scripts/torii.sh"
migrate = "sozo build && sozo migrate apply"
spawn = "./scripts/spawn.sh"
move = "./scripts/move.sh"

[dependencies]
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v1.0.0" }

[[target.starknet-contract]]
build-external-contracts = ["dojo::world::world_contract::world"]

[dev-dependencies]
dojo_cairo_test = { git = "https://github.com/dojoengine/dojo", tag = "v1.0.0" }
