kind = "DojoContract"
class_hash = "0x38d5cfa4cf3c4e9eefa1f908e24c04effd537736c2d243136cfebfce87bf1cc"
original_class_hash = "0x38d5cfa4cf3c4e9eefa1f908e24c04effd537736c2d243136cfebfce87bf1cc"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/dojo_starter-dust_systems-13af1901.json"
reads = []
writes = []
init_calldata = []
tag = "dojo_starter-dust_systems"
systems = [
    "claim_dust",
    "update_dust_pool",
    "enter_dust_pool",
]
manifest_name = "dojo_starter-dust_systems-13af1901"
