kind = "DojoContract"
class_hash = "0x55c8756b30d8be2e241214e7598b4ba7dcc55bb0719801f66a2ab2a07a2484e"
original_class_hash = "0x55c8756b30d8be2e241214e7598b4ba7dcc55bb0719801f66a2ab2a07a2484e"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/dojo_starter-creation_systems-5ad2afd7.json"
reads = []
writes = []
init_calldata = []
tag = "dojo_starter-creation_systems"
systems = [
    "create_galaxy",
    "create_protostar",
    "form_star",
    "form_asteroids",
    "create_asteroid_cluster",
]
manifest_name = "dojo_starter-creation_systems-5ad2afd7"
