kind = "DojoContract"
class_hash = "0x2bb9d4eaca92f2a8bc42291f5f37e8cc8e7a6799e5a1873aec37f0e07156b20"
original_class_hash = "0x2bb9d4eaca92f2a8bc42291f5f37e8cc8e7a6799e5a1873aec37f0e07156b20"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/dojo_starter-authority_systems-3519c229.json"
reads = []
writes = []
init_calldata = []
tag = "dojo_starter-authority_systems"
systems = ["transfer_ownership"]
manifest_name = "dojo_starter-authority_systems-3519c229"
