kind = "DojoContract"
class_hash = "0x647a8235e32dcfa38e3504bc6041391084f63b17ecc17572a48d6fadafb0043"
original_class_hash = "0x647a8235e32dcfa38e3504bc6041391084f63b17ecc17572a48d6fadafb0043"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/dojo_starter-body_movement-60799781.json"
reads = []
writes = []
init_calldata = []
tag = "dojo_starter-body_movement"
systems = [
    "begin_travel",
    "enter_orbit",
    "exit_orbit",
]
manifest_name = "dojo_starter-body_movement-60799781"
