kind = "DojoContract"
class_hash = "0x14ba475c079905c3ba494f87b681b6532916b7eee95272a722a1978ba7a3226"
original_class_hash = "0x14ba475c079905c3ba494f87b681b6532916b7eee95272a722a1978ba7a3226"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/dojo_starter-dust_system-5571bfc9.json"
reads = []
writes = []
init_calldata = []
tag = "dojo_starter-dust_system"
systems = [
    "form_dust_pool",
    "enter_dust_pool",
    "exit_dust_pool",
    "claim_dust",
    "update_dust_pool",
    "consume_dust",
]
manifest_name = "dojo_starter-dust_system-5571bfc9"
