kind = "DojoContract"
class_hash = "0x5def7577a8a4b61d033f6ad9aaf09810a020bf3fc94a48b8c155e9e809a9278"
original_class_hash = "0x5def7577a8a4b61d033f6ad9aaf09810a020bf3fc94a48b8c155e9e809a9278"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/dojo_starter-body_creation-3fc869c7.json"
reads = []
writes = []
init_calldata = []
tag = "dojo_starter-body_creation"
systems = [
    "create_protostar",
    "form_star",
    "form_asteroids",
    "create_asteroid_cluster",
]
manifest_name = "dojo_starter-body_creation-3fc869c7"
