kind = "DojoContract"
class_hash = "0x6d0522e47717a6bd7d1545b67a83fc946734195588332efcd8f93b13f6abd89"
original_class_hash = "0x6d0522e47717a6bd7d1545b67a83fc946734195588332efcd8f93b13f6abd89"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/dojo_starter-body_creation-3fc869c7.json"
reads = []
writes = []
init_calldata = []
tag = "dojo_starter-body_creation"
systems = [
    "create_galaxy",
    "create_protostar",
    "form_star",
    "form_asteroids",
    "create_asteroid_cluster",
]
manifest_name = "dojo_starter-body_creation-3fc869c7"
