kind = "DojoContract"
class_hash = "0x45dae84e1d0a05f08ba05c6fdf456c41a67a1d34d5cb271112f437bea8c14c"
original_class_hash = "0x45dae84e1d0a05f08ba05c6fdf456c41a67a1d34d5cb271112f437bea8c14c"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/dojo_starter-dust_systems-13af1901.json"
reads = []
writes = []
init_calldata = []
tag = "dojo_starter-dust_systems"
systems = [
    "enter_dust_pool",
    "exit_dust_pool",
    "claim_dust",
    "update_dust_pool",
    "consume_dust",
]
manifest_name = "dojo_starter-dust_systems-13af1901"
