kind = "DojoContract"
class_hash = "0x3df6f87c9aad5a7abdae6e9dc7da349deea3ca9cc63e13caead5aa64984270e"
original_class_hash = "0x3df6f87c9aad5a7abdae6e9dc7da349deea3ca9cc63e13caead5aa64984270e"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/dojo_starter-formations-3493261a.json"
reads = []
writes = []
init_calldata = []
tag = "dojo_starter-formations"
systems = ["spawn"]
manifest_name = "dojo_starter-formations-3493261a"
