kind = "DojoContract"
class_hash = "0x711005b203b71d5d72a96778ac74198f137d45b67b0554e9b6ec5d04da907f"
original_class_hash = "0x711005b203b71d5d72a96778ac74198f137d45b67b0554e9b6ec5d04da907f"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/dojo_starter-creation_systems-5ad2afd7.json"
reads = []
writes = []
init_calldata = []
tag = "dojo_starter-creation_systems"
systems = [
    "create_galaxy",
    "create_protostar",
    "form_star",
    "form_asteroids",
    "create_asteroid_cluster",
]
manifest_name = "dojo_starter-creation_systems-5ad2afd7"
