kind = "DojoContract"
class_hash = "0x807ffccbb5dfe3ee5e1e1f182fc66b5ce18429de62f3dfb8ad4ac6052a71af"
original_class_hash = "0x807ffccbb5dfe3ee5e1e1f182fc66b5ce18429de62f3dfb8ad4ac6052a71af"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/dojo_starter-creation_systems-5ad2afd7.json"
reads = []
writes = []
init_calldata = []
tag = "dojo_starter-creation_systems"
systems = [
    "form_star",
    "form_asteroids",
]
manifest_name = "dojo_starter-creation_systems-5ad2afd7"
