kind = "DojoContract"
class_hash = "0x610ec9f134ef1dbaee2e1d0839e6f310728275d2e48a438c5fc8b6862c7f096"
original_class_hash = "0x610ec9f134ef1dbaee2e1d0839e6f310728275d2e48a438c5fc8b6862c7f096"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/dojo_starter-loosh-1cad28b0.json"
reads = []
writes = []
init_calldata = []
tag = "dojo_starter-loosh"
systems = [
    "claim_loosh",
    "send_loosh",
    "consume_loosh",
    "reference_archetype",
]
manifest_name = "dojo_starter-loosh-1cad28b0"
