kind = "DojoContract"
class_hash = "0x6ef2926614bf2f1f60c55bffc7b51cc8fa45c3296147ec58116770495dd1173"
original_class_hash = "0x6ef2926614bf2f1f60c55bffc7b51cc8fa45c3296147ec58116770495dd1173"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/dojo_starter-dust_system-5571bfc9.json"
reads = []
writes = []
init_calldata = []
tag = "dojo_starter-dust_system"
systems = [
    "form_dust_pool",
    "enter_dust_pool",
    "exit_dust_pool",
    "claim_dust",
    "update_dust_pool",
    "consume_dust",
]
manifest_name = "dojo_starter-dust_system-5571bfc9"
