kind = "DojoContract"
class_hash = "0x1115858c8efc6a884ffae77ee259cbdf0e330aeb3ebc574e2b97650bd99a660"
original_class_hash = "0x1115858c8efc6a884ffae77ee259cbdf0e330aeb3ebc574e2b97650bd99a660"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/dojo_starter-dust_system-5571bfc9.json"
reads = []
writes = []
init_calldata = []
tag = "dojo_starter-dust_system"
systems = [
    "form_dust_pool",
    "enter_dust_pool",
    "exit_dust_pool",
    "claim_dust",
    "update_dust_pool",
    "consume_dust",
]
manifest_name = "dojo_starter-dust_system-5571bfc9"
