kind = "DojoContract"
class_hash = "0x2fb2b19dc3370064f2e6c758d3ba7eb00e2ce9bdc19f22ed37e8028fc2cd11c"
original_class_hash = "0x2fb2b19dc3370064f2e6c758d3ba7eb00e2ce9bdc19f22ed37e8028fc2cd11c"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/dojo_starter-creation_systems-5ad2afd7.json"
reads = []
writes = []
init_calldata = []
tag = "dojo_starter-creation_systems"
systems = [
    "create_galaxy",
    "create_protostar",
    "form_star",
    "form_asteroids",
    "create_asteroid_cluster",
]
manifest_name = "dojo_starter-creation_systems-5ad2afd7"
