kind = "DojoContract"
class_hash = "0x6d8fdacdeafd2614dd199c6fc8b2dfa4c136b5db453f302f4eee004a8f079e7"
original_class_hash = "0x6d8fdacdeafd2614dd199c6fc8b2dfa4c136b5db453f302f4eee004a8f079e7"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/dojo_starter-creation_systems-5ad2afd7.json"
reads = []
writes = []
init_calldata = []
tag = "dojo_starter-creation_systems"
systems = [
    "form_star",
    "form_asteroids",
]
manifest_name = "dojo_starter-creation_systems-5ad2afd7"
