kind = "DojoContract"
class_hash = "0x47442e8e2d5456e05e33374b83ad7dcfb62239779fab677aebd3d4c8364bd42"
original_class_hash = "0x47442e8e2d5456e05e33374b83ad7dcfb62239779fab677aebd3d4c8364bd42"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/dojo_starter-dust_systems-13af1901.json"
reads = []
writes = []
init_calldata = []
tag = "dojo_starter-dust_systems"
systems = [
    "claim_dust",
    "update_dust_pool",
]
manifest_name = "dojo_starter-dust_systems-13af1901"
