kind = "DojoContract"
class_hash = "0x5968063b84bc4a2278f92222f60db511acb64c9b438516431e44ef875a93278"
original_class_hash = "0x5968063b84bc4a2278f92222f60db511acb64c9b438516431e44ef875a93278"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/dojo_starter-mass_systems-36599faa.json"
reads = []
writes = []
init_calldata = []
tag = "dojo_starter-mass_systems"
systems = ["transfer_mass"]
manifest_name = "dojo_starter-mass_systems-36599faa"
