kind = "DojoContract"
class_hash = "0x1ad31133e2fd15f247ca173e3dce128ad39d8e8484822aafb451fe457eb2121"
original_class_hash = "0x1ad31133e2fd15f247ca173e3dce128ad39d8e8484822aafb451fe457eb2121"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/dojo_starter-loosh_systems-504b5a92.json"
reads = []
writes = []
init_calldata = []
tag = "dojo_starter-loosh_systems"
systems = [
    "l1_receive_loosh",
    "transfer_loosh",
    "burn_loosh",
]
manifest_name = "dojo_starter-loosh_systems-504b5a92"
