kind = "DojoContract"
class_hash = "0x3cdb86d38336034048e6d8024e9028850712fe59159c2aee78eeabf649dcc85"
original_class_hash = "0x3cdb86d38336034048e6d8024e9028850712fe59159c2aee78eeabf649dcc85"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/dojo_starter-loosh_system-50c10825.json"
reads = []
writes = []
init_calldata = []
tag = "dojo_starter-loosh_system"
systems = [
    "l1_receive_loosh",
    "send_loosh",
    "burn_loosh",
    "reference_archetype",
]
manifest_name = "dojo_starter-loosh_system-50c10825"
