kind = "DojoContract"
class_hash = "0x348b7256d567ea320b78dc7e00d44ca9e898729c304e35aa77ab6f3cdc58af6"
original_class_hash = "0x348b7256d567ea320b78dc7e00d44ca9e898729c304e35aa77ab6f3cdc58af6"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/dojo_starter-body_creation-3fc869c7.json"
reads = []
writes = []
init_calldata = []
tag = "dojo_starter-body_creation"
systems = [
    "spawn_protostar",
    "form_star",
    "form_asteroids",
    "define_new_asteroid_cluster",
]
manifest_name = "dojo_starter-body_creation-3fc869c7"
