kind = "DojoContract"
class_hash = "0x4006c41efafdb31ca0bcd4a4ae5132cc61cdeb951b413306c6d8c27a6c73b1f"
original_class_hash = "0x4006c41efafdb31ca0bcd4a4ae5132cc61cdeb951b413306c6d8c27a6c73b1f"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/dojo_starter-dust_systems-13af1901.json"
reads = []
writes = []
init_calldata = []
tag = "dojo_starter-dust_systems"
systems = [
    "claim_dust",
    "update_emission",
    "enter_dust_pool",
    "begin_dust_harvest",
    "end_dust_harvest",
    "cancel_dust_harvest",
]
manifest_name = "dojo_starter-dust_systems-13af1901"
