kind = "DojoContract"
class_hash = "0x326c32990616d3992789a353e8f525f7c9dc12fad0e2733fc12710c4f695b1f"
original_class_hash = "0x326c32990616d3992789a353e8f525f7c9dc12fad0e2733fc12710c4f695b1f"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/dojo_starter-dust_systems-13af1901.json"
reads = []
writes = []
init_calldata = []
tag = "dojo_starter-dust_systems"
systems = [
    "claim_dust",
    "update_dust_pool",
    "enter_dust_pool",
]
manifest_name = "dojo_starter-dust_systems-13af1901"
