kind = "DojoContract"
class_hash = "0x6644ee98a296744ba81f760399d6f344e2765d5c6231c6b5a82696083e5b08b"
original_class_hash = "0x6644ee98a296744ba81f760399d6f344e2765d5c6231c6b5a82696083e5b08b"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/dojo_starter-mass_systems-36599faa.json"
reads = []
writes = []
init_calldata = []
tag = "dojo_starter-mass_systems"
systems = ["transfer_mass"]
manifest_name = "dojo_starter-mass_systems-36599faa"
