kind = "DojoContract"
class_hash = "0x346b29760cf954a2b7a2bc225fe8cb54a61fcae0281df162b1d65bee3ee366b"
original_class_hash = "0x346b29760cf954a2b7a2bc225fe8cb54a61fcae0281df162b1d65bee3ee366b"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/dojo_starter-dust_systems-13af1901.json"
reads = []
writes = []
init_calldata = []
tag = "dojo_starter-dust_systems"
systems = [
    "claim_dust",
    "update_dust_pool",
]
manifest_name = "dojo_starter-dust_systems-13af1901"
