kind = "DojoContract"
class_hash = "0x763c26b939baad20046e61aa805a3870804b20abe4d54f765e0a8f18d903405"
original_class_hash = "0x763c26b939baad20046e61aa805a3870804b20abe4d54f765e0a8f18d903405"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/dojo_starter-movement_systems-3b0b90be.json"
reads = []
writes = []
init_calldata = []
tag = "dojo_starter-movement_systems"
systems = [
    "begin_travel",
    "enter_orbit",
    "exit_orbit",
]
manifest_name = "dojo_starter-movement_systems-3b0b90be"
