kind = "DojoContract"
class_hash = "0x256864b76d37f9cc7318129bde73595e8f3f7722df01e481f676e55e421daef"
original_class_hash = "0x256864b76d37f9cc7318129bde73595e8f3f7722df01e481f676e55e421daef"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/dojo_starter-movement_systems-3b0b90be.json"
reads = []
writes = []
init_calldata = []
tag = "dojo_starter-movement_systems"
systems = [
    "begin_travel",
    "end_travel",
    "enter_orbit",
    "exit_orbit",
]
manifest_name = "dojo_starter-movement_systems-3b0b90be"
