kind = "DojoContract"
class_hash = "0x2d190a36241c0cf3bdf9edd70b635228756897dfef2d1dc32ac707d490a967b"
original_class_hash = "0x2d190a36241c0cf3bdf9edd70b635228756897dfef2d1dc32ac707d490a967b"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/astraplani-config_systems-78d3837b.json"
reads = []
writes = []
init_calldata = []
tag = "astraplani-config_systems"
systems = [
    "set_admin_config",
    "set_dust_value_config",
    "set_dust_emission_config",
    "set_harvest_time",
    "set_base_cosmic_body_mass",
    "set_min_orbit_center_mass",
    "set_max_cosmic_body_mass",
    "set_loosh_cost",
    "set_travel_speed",
    "set_incubation_time",
]
manifest_name = "astraplani-config_systems-78d3837b"
