kind = "DojoContract"
class_hash = "0x5b451498704b616ecaf701c408852a0dcf658e08aa77c1e7d09eec025e0a825"
original_class_hash = "0x5b451498704b616ecaf701c408852a0dcf658e08aa77c1e7d09eec025e0a825"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/astraplani-authority_systems-79ed83b1.json"
reads = []
writes = []
init_calldata = []
tag = "astraplani-authority_systems"
systems = ["transfer_ownership"]
manifest_name = "astraplani-authority_systems-79ed83b1"
