kind = "DojoContract"
class_hash = "0x723940533a4800e2a48fcb0cf25722cb7867e902fbaad986f26f6c3dd2a9e04"
original_class_hash = "0x723940533a4800e2a48fcb0cf25722cb7867e902fbaad986f26f6c3dd2a9e04"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/astraplani-dust_systems-187f0a61.json"
reads = []
writes = []
init_calldata = []
tag = "astraplani-dust_systems"
systems = [
    "claim_dust",
    "update_emission",
    "enter_dust_pool",
    "begin_dust_harvest",
    "end_dust_harvest",
    "cancel_dust_harvest",
]
manifest_name = "astraplani-dust_systems-187f0a61"
