kind = "DojoContract"
class_hash = "0x3283025662784af1374e74f3f4b5298619aa5e10493ed0df56d5a2decb92df0"
original_class_hash = "0x3283025662784af1374e74f3f4b5298619aa5e10493ed0df56d5a2decb92df0"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/astraplani-config_systems-78d3837b.json"
reads = []
writes = []
init_calldata = []
tag = "astraplani-config_systems"
systems = [
    "set_admin_config",
    "set_dust_value_config",
    "set_dust_emission_config",
    "set_harvest_time",
    "set_base_cosmic_body_mass",
    "set_min_orbit_center_mass",
    "set_max_cosmic_body_mass",
    "set_loosh_cost",
    "set_travel_speed",
]
manifest_name = "astraplani-config_systems-78d3837b"
