kind = "DojoContract"
class_hash = "0x356df06b5d7cb9948034a98bb85e36156e1f90d435581293000ee991eb5853b"
original_class_hash = "0x356df06b5d7cb9948034a98bb85e36156e1f90d435581293000ee991eb5853b"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/astraplani-creation_systems-52c9602e.json"
reads = []
writes = []
init_calldata = []
tag = "astraplani-creation_systems"
systems = [
    "form_star",
    "form_asteroids",
]
manifest_name = "astraplani-creation_systems-52c9602e"
