kind = "DojoContract"
class_hash = "0x283eaa7892285682bea79c8a41f5a7ac8f8ee2a5756469dbc5d26493a5ae9f7"
original_class_hash = "0x283eaa7892285682bea79c8a41f5a7ac8f8ee2a5756469dbc5d26493a5ae9f7"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/astraplani-mass_systems-393abc17.json"
reads = []
writes = []
init_calldata = []
tag = "astraplani-mass_systems"
systems = ["transfer_mass"]
manifest_name = "astraplani-mass_systems-393abc17"
