kind = "DojoModel"
class_hash = "0x24577a4f37ee41b443de7439909dfbf450d7a059836510434d97836811c65a4"
original_class_hash = "0x24577a4f37ee41b443de7439909dfbf450d7a059836510434d97836811c65a4"
abi = "manifests/dev/base/abis/models/dojo_starter-LooshCostConfig-657ea5ab.json"
tag = "dojo_starter-LooshCostConfig"
qualified_path = "dojo_starter::models::config::loosh_cost_config"
manifest_name = "dojo_starter-LooshCostConfig-657ea5ab"

[[members]]
name = "config_id"
type = "u32"
key = true

[[members]]
name = "base_travel_cost"
type = "u128"
key = false

[[members]]
name = "base_creation_cost"
type = "u128"
key = false
