kind = "DojoModel"
class_hash = "0x84e243f594bac679e448ada52e1b9a661acead90ecb950eeac07a719fa3bb7"
original_class_hash = "0x84e243f594bac679e448ada52e1b9a661acead90ecb950eeac07a719fa3bb7"
abi = "manifests/dev/base/abis/models/dojo_starter-LooshBalance-1b3f3b11.json"
tag = "dojo_starter-LooshBalance"
qualified_path = "dojo_starter::models::loosh_balance::loosh_balance"
manifest_name = "dojo_starter-LooshBalance-1b3f3b11"

[[members]]
name = "entity"
type = "ContractAddress"
key = true

[[members]]
name = "loosh"
type = "u128"
key = false
