kind = "DojoModel"
class_hash = "0x77f12b3eda3de2380744a6995dfcccf6f0eaca5e0a881a8575435dff09d6fd7"
original_class_hash = "0x77f12b3eda3de2380744a6995dfcccf6f0eaca5e0a881a8575435dff09d6fd7"
abi = "manifests/dev/base/abis/models/dojo_starter-DustValueConfig-64042016.json"
tag = "dojo_starter-DustValueConfig"
qualified_path = "dojo_starter::models::config::dust_value_config"
manifest_name = "dojo_starter-DustValueConfig-64042016"

[[members]]
name = "config_id"
type = "u32"
key = true

[[members]]
name = "dust_to_mass"
type = "u128"
key = false
