kind = "DojoModel"
class_hash = "0x218a13b150a5ad1aabda0154bec8239b20714ae353be464896da0606ed6a989"
original_class_hash = "0x218a13b150a5ad1aabda0154bec8239b20714ae353be464896da0606ed6a989"
abi = "manifests/dev/base/abis/models/dojo_starter-BasalAttributes-4bf505e2.json"
tag = "dojo_starter-BasalAttributes"
qualified_path = "dojo_starter::models::basal_attributes::basal_attributes"
manifest_name = "dojo_starter-BasalAttributes-4bf505e2"

[[members]]
name = "entity"
type = "u32"
key = true

[[members]]
name = "attributes"
type = "u8"
key = false
