kind = "DojoModel"
class_hash = "0x7153c948bc66a3c406bcd6d56a6d83b87a6fada927de1968d41e3e6f689a7bc"
original_class_hash = "0x7153c948bc66a3c406bcd6d56a6d83b87a6fada927de1968d41e3e6f689a7bc"
abi = "manifests/dev/base/abis/models/dojo_starter-BodiesCollided-31f2c334.json"
tag = "dojo_starter-BodiesCollided"
qualified_path = "dojo_starter::systems::movement_systems::movement_systems::bodies_collided"
manifest_name = "dojo_starter-BodiesCollided-31f2c334"

[[members]]
name = "body_id"
type = "u32"
key = true

[[members]]
name = "target_id"
type = "u32"
key = false

[[members]]
name = "mass_change_body"
type = "i64"
key = false

[[members]]
name = "mass_change_target"
type = "i64"
key = false
