kind = "DojoModel"
class_hash = "0x1de7796071b5dbd31ea500aaea3cdb9838096ce5e9bd9b3f460e71e6e5f8c4"
original_class_hash = "0x1de7796071b5dbd31ea500aaea3cdb9838096ce5e9bd9b3f460e71e6e5f8c4"
abi = "manifests/dev/base/abis/models/dojo_starter-CosmicBody-5b7c667e.json"
tag = "dojo_starter-CosmicBody"
qualified_path = "dojo_starter::models::cosmic_body::cosmic_body"
manifest_name = "dojo_starter-CosmicBody-5b7c667e"

[[members]]
name = "entity"
type = "u32"
key = true

[[members]]
name = "body_type"
type = "CosmicBodyType"
key = false
