kind = "DojoModel"
class_hash = "0x1741d1f8ec09edf09a63f097f8b6aec2d54195b5e65bc9015a8d4136f03113d"
original_class_hash = "0x1741d1f8ec09edf09a63f097f8b6aec2d54195b5e65bc9015a8d4136f03113d"
abi = "manifests/dev/base/abis/models/dojo_starter-AsteroidsFormed-47175954.json"
tag = "dojo_starter-AsteroidsFormed"
qualified_path = "dojo_starter::systems::creation_systems::creation_systems::asteroids_formed"
manifest_name = "dojo_starter-AsteroidsFormed-47175954"

[[members]]
name = "star_id"
type = "u32"
key = true

[[members]]
name = "cluster_id"
type = "u32"
key = false
