kind = "DojoModel"
class_hash = "0x74d3ce1178d5dc1d4b4180423d9efa195a4eaf28d54a62cb1e39850e0ffe252"
original_class_hash = "0x74d3ce1178d5dc1d4b4180423d9efa195a4eaf28d54a62cb1e39850e0ffe252"
abi = "manifests/dev/base/abis/models/dojo_starter-ProtostarSpawned-3d593013.json"
tag = "dojo_starter-ProtostarSpawned"
qualified_path = "dojo_starter::systems::creation_systems::creation_systems::protostar_spawned"
manifest_name = "dojo_starter-ProtostarSpawned-3d593013"

[[members]]
name = "body_id"
type = "u32"
key = true

[[members]]
name = "x"
type = "u64"
key = false

[[members]]
name = "y"
type = "u64"
key = false
