kind = "DojoModel"
class_hash = "0x681dea943833c87ffa58dd9def6e214149c52293d8a5c3f33755a6869cad207"
original_class_hash = "0x681dea943833c87ffa58dd9def6e214149c52293d8a5c3f33755a6869cad207"
abi = "manifests/dev/base/abis/models/dojo_starter-LooshMinted-4210b5ee.json"
tag = "dojo_starter-LooshMinted"
qualified_path = "dojo_starter::systems::loosh_systems::loosh_systems::loosh_minted"
manifest_name = "dojo_starter-LooshMinted-4210b5ee"

[[members]]
name = "receiver"
type = "ContractAddress"
key = true

[[members]]
name = "amount"
type = "u128"
key = false
