kind = "DojoModel"
class_hash = "0x44d03428f6d80c8ce0950835e08294df87714cef0016d97341158763140f943"
original_class_hash = "0x44d03428f6d80c8ce0950835e08294df87714cef0016d97341158763140f943"
abi = "manifests/dev/base/abis/models/dojo_starter-BodyMoved-67a1ead8.json"
tag = "dojo_starter-BodyMoved"
qualified_path = "dojo_starter::systems::movement_systems::movement_systems::body_moved"
manifest_name = "dojo_starter-BodyMoved-67a1ead8"

[[members]]
name = "body_id"
type = "u32"
key = true

[[members]]
name = "new_x"
type = "u64"
key = false

[[members]]
name = "new_y"
type = "u64"
key = false
