kind = "DojoModel"
class_hash = "0x22d4099d61019d173de64fbcc97725d3070d5224af329c27bff2ce163db7e85"
original_class_hash = "0x22d4099d61019d173de64fbcc97725d3070d5224af329c27bff2ce163db7e85"
abi = "manifests/dev/base/abis/models/dojo_starter-AsteroidClusterDefined-112fe115.json"
tag = "dojo_starter-AsteroidClusterDefined"
qualified_path = "dojo_starter::systems::creation_systems::creation_systems::asteroid_cluster_defined"
manifest_name = "dojo_starter-AsteroidClusterDefined-112fe115"

[[members]]
name = "star_id"
type = "u32"
key = true

[[members]]
name = "cluster_id"
type = "u32"
key = false
