kind = "DojoModel"
class_hash = "0x71427a26af47c9fdb5dc45ec327ebca424c3f8ab09137e2882f524bab40f2e"
original_class_hash = "0x71427a26af47c9fdb5dc45ec327ebca424c3f8ab09137e2882f524bab40f2e"
abi = "manifests/dev/base/abis/models/dojo_starter-OrbitalMass-74ba3ba9.json"
tag = "dojo_starter-OrbitalMass"
qualified_path = "dojo_starter::models::orbital_mass::orbital_mass"
manifest_name = "dojo_starter-OrbitalMass-74ba3ba9"

[[members]]
name = "entity"
type = "u32"
key = true

[[members]]
name = "orbital_mass"
type = "u64"
key = false
