kind = "DojoModel"
class_hash = "0x583855befbb6225aa1676b85e8a3ef03f4a37b634498805854e5d04c6daf56e"
original_class_hash = "0x583855befbb6225aa1676b85e8a3ef03f4a37b634498805854e5d04c6daf56e"
abi = "manifests/dev/base/abis/models/dojo_starter-DustCloud-4a83a4a4.json"
tag = "dojo_starter-DustCloud"
qualified_path = "dojo_starter::models::dust_cloud::dust_cloud"
manifest_name = "dojo_starter-DustCloud-4a83a4a4"

[[members]]
name = "x"
type = "u64"
key = true

[[members]]
name = "y"
type = "u64"
key = true

[[members]]
name = "orbit_center"
type = "u32"
key = true

[[members]]
name = "dust_balance"
type = "u128"
key = false
