kind = "DojoModel"
class_hash = "0x7c85d8d8e2283d9b52bbd0760b0f7cedcf0b319b76094da9a5172e29ec0157e"
original_class_hash = "0x7c85d8d8e2283d9b52bbd0760b0f7cedcf0b319b76094da9a5172e29ec0157e"
abi = "manifests/dev/base/abis/models/dojo_starter-BasalAttributes-4bf505e2.json"
tag = "dojo_starter-BasalAttributes"
qualified_path = "dojo_starter::models::basal_attributes::basal_attributes"
manifest_name = "dojo_starter-BasalAttributes-4bf505e2"

[[members]]
name = "entity"
type = "ContractAddress"
key = true

[[members]]
name = "attributes"
type = "u8"
key = false
