kind = "DojoModel"
class_hash = "0x37eb3a88970b20b18f1017593c4757f0897ebe5448d0a71e0df9688a21b8a4a"
original_class_hash = "0x37eb3a88970b20b18f1017593c4757f0897ebe5448d0a71e0df9688a21b8a4a"
abi = "manifests/dev/base/abis/models/dojo_starter-Orbit-321dcae1.json"
tag = "dojo_starter-Orbit"
qualified_path = "dojo_starter::models::orbit::orbit"
manifest_name = "dojo_starter-Orbit-321dcae1"

[[members]]
name = "entity"
type = "u32"
key = true

[[members]]
name = "orbit_center"
type = "u32"
key = false
