kind = "DojoModel"
class_hash = "0x21250c9a1a428a48bca668fd1e1d19af7c666e1cf879f3925c9eacbef3b10bb"
original_class_hash = "0x21250c9a1a428a48bca668fd1e1d19af7c666e1cf879f3925c9eacbef3b10bb"
abi = "manifests/dev/base/abis/models/dojo_starter-LooshBalance-1b3f3b11.json"
tag = "dojo_starter-LooshBalance"
qualified_path = "dojo_starter::models::loosh_balance::loosh_balance"
manifest_name = "dojo_starter-LooshBalance-1b3f3b11"

[[members]]
name = "address"
type = "ContractAddress"
key = true

[[members]]
name = "balance"
type = "u128"
key = false
