kind = "DojoModel"
class_hash = "0x4acbeeb0f276ddecebc3d056d2065b7479606ee2f99c9bb78ca13403656da06"
original_class_hash = "0x4acbeeb0f276ddecebc3d056d2065b7479606ee2f99c9bb78ca13403656da06"
abi = "manifests/dev/base/abis/models/dojo_starter-DustClaimed-27301d95.json"
tag = "dojo_starter-DustClaimed"
qualified_path = "dojo_starter::systems::dust::contracts::dust_systems::dust_systems::dust_claimed"
manifest_name = "dojo_starter-DustClaimed-27301d95"

[[members]]
name = "body_id"
type = "u32"
key = true

[[members]]
name = "amount"
type = "u128"
key = false
