kind = "DojoModel"
class_hash = "0x60497858b1b089daaf18ce45446ab0f3c73583c79b12e3b3b3c76c89026cd2c"
original_class_hash = "0x60497858b1b089daaf18ce45446ab0f3c73583c79b12e3b3b3c76c89026cd2c"
abi = "manifests/dev/base/abis/models/dojo_starter-MaxCosmicBodyMassConfig-4a69ce79.json"
tag = "dojo_starter-MaxCosmicBodyMassConfig"
qualified_path = "dojo_starter::models::config::max_cosmic_body_mass_config"
manifest_name = "dojo_starter-MaxCosmicBodyMassConfig-4a69ce79"

[[members]]
name = "config_id"
type = "u32"
key = true

[[members]]
name = "max_asteroid_cluster_mass"
type = "u64"
key = false
