kind = "DojoModel"
class_hash = "0x59f76bf9d2cf0cc4620250bc5d861d3cb04e6fd9b3c15af148ab59979a7bf13"
original_class_hash = "0x59f76bf9d2cf0cc4620250bc5d861d3cb04e6fd9b3c15af148ab59979a7bf13"
abi = "manifests/dev/base/abis/models/dojo_starter-HarvestAction-9146ccc6.json"
tag = "dojo_starter-HarvestAction"
qualified_path = "dojo_starter::models::harvest_action::harvest_action"
manifest_name = "dojo_starter-HarvestAction-9146ccc6"

[[members]]
name = "entity"
type = "u32"
key = true

[[members]]
name = "start_ts"
type = "u64"
key = false

[[members]]
name = "end_ts"
type = "u64"
key = false

[[members]]
name = "harvest_amount"
type = "u128"
key = false
