kind = "DojoModel"
class_hash = "0x2e4ae20ee5c00831cf77f94cf754f246b19059c2e7f0a52bfd290f6233bc76d"
original_class_hash = "0x2e4ae20ee5c00831cf77f94cf754f246b19059c2e7f0a52bfd290f6233bc76d"
abi = "manifests/dev/base/abis/models/dojo_starter-TravelAction-1be38c70.json"
tag = "dojo_starter-TravelAction"
qualified_path = "dojo_starter::models::travel_action::travel_action"
manifest_name = "dojo_starter-TravelAction-1be38c70"

[[members]]
name = "entity"
type = "ContractAddress"
key = true

[[members]]
name = "depart_ts"
type = "u64"
key = false

[[members]]
name = "arrival_ts"
type = "u64"
key = false

[[members]]
name = "target_position"
type = "Vec2"
key = false
