kind = "DojoModel"
class_hash = "0x3396d4c58a76f95031d577acadb06bfb4c63fe4796bf435299235621164c28f"
original_class_hash = "0x3396d4c58a76f95031d577acadb06bfb4c63fe4796bf435299235621164c28f"
abi = "manifests/dev/base/abis/models/dojo_starter-DustClaimed-27301d95.json"
tag = "dojo_starter-DustClaimed"
qualified_path = "dojo_starter::systems::dust_systems::dust_systems::dust_claimed"
manifest_name = "dojo_starter-DustClaimed-27301d95"

[[members]]
name = "body_id"
type = "u32"
key = true

[[members]]
name = "amount"
type = "u128"
key = false
