kind = "DojoModel"
class_hash = "0x3c5f97aac1d919df5e877810278850a85382a5c96cab03763fce44dd89fe4a8"
original_class_hash = "0x3c5f97aac1d919df5e877810278850a85382a5c96cab03763fce44dd89fe4a8"
abi = "manifests/dev/base/abis/models/dojo_starter-StarFormed-4b442116.json"
tag = "dojo_starter-StarFormed"
qualified_path = "dojo_starter::systems::creation_systems::creation_systems::star_formed"
manifest_name = "dojo_starter-StarFormed-4b442116"

[[members]]
name = "protostar_id"
type = "u32"
key = true

[[members]]
name = "timestamp"
type = "u64"
key = false
