kind = "DojoModel"
class_hash = "0x5b105dd6a3d08d2b65aeaf97d1ed5447182262a4f6e4c86a4dd971e4281a0b1"
original_class_hash = "0x5b105dd6a3d08d2b65aeaf97d1ed5447182262a4f6e4c86a4dd971e4281a0b1"
abi = "manifests/dev/base/abis/models/dojo_starter-TravelAction-1be38c70.json"
tag = "dojo_starter-TravelAction"
qualified_path = "dojo_starter::models::travel_action::travel_action"
manifest_name = "dojo_starter-TravelAction-1be38c70"

[[members]]
name = "entity"
type = "u32"
key = true

[[members]]
name = "depart_ts"
type = "u64"
key = false

[[members]]
name = "arrival_ts"
type = "u64"
key = false

[[members]]
name = "target_position"
type = "Vec2"
key = false
