kind = "DojoModel"
class_hash = "0x2cb1ebf7afe043db600cea78ffa70173b298bf417d2664a907459c1c0ffcdcd"
original_class_hash = "0x2cb1ebf7afe043db600cea78ffa70173b298bf417d2664a907459c1c0ffcdcd"
abi = "manifests/dev/base/abis/models/dojo_starter-DustPoolEntered-ba6ef78e.json"
tag = "dojo_starter-DustPoolEntered"
qualified_path = "dojo_starter::systems::dust::contracts::dust_systems::dust_systems::dust_pool_entered"
manifest_name = "dojo_starter-DustPoolEntered-ba6ef78e"

[[members]]
name = "body_id"
type = "u32"
key = true

[[members]]
name = "pool_id"
type = "u32"
key = false
