kind = "DojoModel"
class_hash = "0x79c1229f346c918e836368c16aa0c7e0a440985707d66a559cd5b7f6ecefead"
original_class_hash = "0x79c1229f346c918e836368c16aa0c7e0a440985707d66a559cd5b7f6ecefead"
abi = "manifests/dev/base/abis/models/dojo_starter-AsteroidsFormed-47175954.json"
tag = "dojo_starter-AsteroidsFormed"
qualified_path = "dojo_starter::systems::creation::contracts::creation_systems::creation_systems::asteroids_formed"
manifest_name = "dojo_starter-AsteroidsFormed-47175954"

[[members]]
name = "star_id"
type = "u32"
key = true

[[members]]
name = "cluster_id"
type = "u32"
key = false
