kind = "DojoModel"
class_hash = "0x3b909cb6a2b25b3c61201a4ed6c55135b6690f49cbc72d34c19176636f9ea40"
original_class_hash = "0x3b909cb6a2b25b3c61201a4ed6c55135b6690f49cbc72d34c19176636f9ea40"
abi = "manifests/dev/base/abis/models/dojo_starter-DustBalance-12915a51.json"
tag = "dojo_starter-DustBalance"
qualified_path = "dojo_starter::models::dust_balance::dust_balance"
manifest_name = "dojo_starter-DustBalance-12915a51"

[[members]]
name = "entity"
type = "u32"
key = true

[[members]]
name = "balance"
type = "u128"
key = false
