kind = "DojoModel"
class_hash = "0x6ddfe9b2b7e00ce1dcfef45b1b5e0d604be86fb9193b71e058502b7be71b02a"
original_class_hash = "0x6ddfe9b2b7e00ce1dcfef45b1b5e0d604be86fb9193b71e058502b7be71b02a"
abi = "manifests/dev/base/abis/models/dojo_starter-DustConsumed-345897b2.json"
tag = "dojo_starter-DustConsumed"
qualified_path = "dojo_starter::systems::dust_systems::dust_systems::dust_consumed"
manifest_name = "dojo_starter-DustConsumed-345897b2"

[[members]]
name = "body_id"
type = "u32"
key = true

[[members]]
name = "amount"
type = "u128"
key = false
