kind = "DojoModel"
class_hash = "0x497a814db9b151a59bfd7078c2c47d0990278197a5ce8590bf9d15579bec703"
original_class_hash = "0x497a814db9b151a59bfd7078c2c47d0990278197a5ce8590bf9d15579bec703"
abi = "manifests/dev/base/abis/models/dojo_starter-LooshTransferred-2f915f92.json"
tag = "dojo_starter-LooshTransferred"
qualified_path = "dojo_starter::systems::loosh_systems::loosh_systems::loosh_transferred"
manifest_name = "dojo_starter-LooshTransferred-2f915f92"

[[members]]
name = "sender"
type = "ContractAddress"
key = true

[[members]]
name = "receiver"
type = "ContractAddress"
key = false

[[members]]
name = "amount"
type = "u128"
key = false
