kind = "DojoModel"
class_hash = "0x39c7262ebd11388be1ad8d94cc51c0958d470c25b9e646660dd93114533f093"
original_class_hash = "0x39c7262ebd11388be1ad8d94cc51c0958d470c25b9e646660dd93114533f093"
abi = "manifests/dev/base/abis/models/dojo_starter-HarvestTimeConfig-7c1e31f7.json"
tag = "dojo_starter-HarvestTimeConfig"
qualified_path = "dojo_starter::models::config::harvest_time_config"
manifest_name = "dojo_starter-HarvestTimeConfig-7c1e31f7"

[[members]]
name = "config_id"
type = "u32"
key = true

[[members]]
name = "min_harvest_time"
type = "u64"
key = false

[[members]]
name = "base_harvest_time"
type = "u64"
key = false
