kind = "DojoModel"
class_hash = "0x2f070568c8e646386f67d43de0a3be93a39e247b1d7f0f63a77d7f30ccf0cb3"
original_class_hash = "0x2f070568c8e646386f67d43de0a3be93a39e247b1d7f0f63a77d7f30ccf0cb3"
abi = "manifests/dev/base/abis/models/dojo_starter-TravelSpeedConfig-34c2bfaa.json"
tag = "dojo_starter-TravelSpeedConfig"
qualified_path = "dojo_starter::models::config::travel_speed_config"
manifest_name = "dojo_starter-TravelSpeedConfig-34c2bfaa"

[[members]]
name = "config_id"
type = "u32"
key = true

[[members]]
name = "base_travel_speed"
type = "u64"
key = false
