kind = "DojoModel"
class_hash = "0x121004ed149bf101f4586fd46fe7989eac98527488465b27458675c85bad76"
original_class_hash = "0x121004ed149bf101f4586fd46fe7989eac98527488465b27458675c85bad76"
abi = "manifests/dev/base/abis/models/dojo_starter-DustPoolFormed-69d11bac.json"
tag = "dojo_starter-DustPoolFormed"
qualified_path = "dojo_starter::systems::dust_systems::dust_systems::dust_pool_formed"
manifest_name = "dojo_starter-DustPoolFormed-69d11bac"

[[members]]
name = "body_id"
type = "u32"
key = true

[[members]]
name = "timestamp"
type = "u64"
key = false
