kind = "DojoModel"
class_hash = "0x5dfc7af909427d43018caf2cfef6b20a57ffe91cf97975b95506c59478cb010"
original_class_hash = "0x5dfc7af909427d43018caf2cfef6b20a57ffe91cf97975b95506c59478cb010"
abi = "manifests/dev/base/abis/models/dojo_starter-AsteroidClusterDefined-112fe115.json"
tag = "dojo_starter-AsteroidClusterDefined"
qualified_path = "dojo_starter::systems::body_creation::body_creation::asteroid_cluster_defined"
manifest_name = "dojo_starter-AsteroidClusterDefined-112fe115"

[[members]]
name = "star_id"
type = "u32"
key = true

[[members]]
name = "cluster_id"
type = "u32"
key = false
