kind = "DojoModel"
class_hash = "0x2dc407efce1caf98e93eba3d5196be3fee6cb31a04434842efbee8b8e52ea12"
original_class_hash = "0x2dc407efce1caf98e93eba3d5196be3fee6cb31a04434842efbee8b8e52ea12"
abi = "manifests/dev/base/abis/models/dojo_starter-DustConsumed-345897b2.json"
tag = "dojo_starter-DustConsumed"
qualified_path = "dojo_starter::systems::dust_system::dust_system::dust_consumed"
manifest_name = "dojo_starter-DustConsumed-345897b2"

[[members]]
name = "body_id"
type = "u32"
key = true

[[members]]
name = "amount"
type = "u128"
key = false
